# Generated by Django 5.0.3 on 2024-03-23 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_emotion'),
    ]

    operations = [
        migrations.AddField(
            model_name='emotion',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
